### ISSUE TITLE
Hard to Use

### ISSUE THREAD

**Issue by elibroftw** [tauri-apps/curriedForage#27]
How would I get the value for a specific key and use a default if it is unavailable? I tried this but defaultColorScheme is a promise.

```js
const defaultColorScheme = forage.getKeyValue('colorScheme')() || 'dark';
console.log(defaultColorScheme);
const [colorScheme, setColorScheme] = useState(defaultColorScheme);
```

**Comment by FabianLars** [comment]
This is a good question to ask the search engine of your choice.
But in react you probably need to use useEffect for this. Either init your state with the fallback value directly or block your UI until the Promise resolves.

**Comment by elibroftw** [comment]
[There](https://www.google.com/search?client=firefox-b-d&q=how+to+use+tauri+forage)

Wow I've been enlightened. I know I need to use useEffects, but how would I getAnItem and return a default value if it does not exist?

**Comment by elibroftw** [comment]
I'm asking because I'm actually trying to use these plugins. I could very well just use emit and handle configuration settings/getting in the Rust backend, but I'm not one to redo the wheel.

**Comment by elibroftw** [comment]
okay, I just decided to use localForage. Didn't realize this itself was a wheel v2.0
